### ISSUE TITLE
Minimum SDK version 16 Reason

### ISSUE THREAD

**Issue by xstherrera1987** [airbnb/RxGroups#35]
Why is the minimum SDK version set to 16? 

Being unfamiliar with the RxGroups codebase, I've scanned [JellyBean Platform Wikipedia](https://en.wikipedia.org/wiki/Android_Jelly_Bean#Platform) and [API 16 Diff Report](https://developer.android.com/sdk/api_diff/16/changes.html) for clues but nothing stands out as obvious.  Can I ignore this ?

eg: 
`<uses-sdk tools:overrideLibrary="com.airbnb.rxgroups.android" />`

**Comment by felipecsl** [comment]
This is the same minSdk that the Airbnb app uses, so that's probably why.
I don't think there's a specific reason for that,we should be able to use a lower sdk version if we're not using any 16+ APIs

**Comment by xstherrera1987** [comment]
the oldest SDK that Robolectric emulates is API-16. Android Studio reports that this covers ~95.2% of active devices,  [Android Dashboards](https://developer.android.com/about/dashboards/index.html) claims 98% over a rolling 7-day period.  So API 16 seems like a reasonable lower bound, though I did override the `minSDK` version and run successfully on SDK 15.

**Comment by felipecsl** [comment]
Should be probably safe to override this to 15 if you want, as described above.
